# Generated by Django 3.2.14 on 2022-07-21 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_title', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('MP', 'Madhya Pradesh'), ('UP', 'Utter Pradesh'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MH', 'Maharashtra')], max_length=100)),
                ('venue_description', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=50)),
                ('featured_package_price', models.IntegerField()),
                ('guests', models.IntegerField()),
                ('amenities', models.CharField(choices=[('Parking Area', 'Parking Area'), ('Air Conditioning', 'Air Conditioning'), ('CCTV', 'CCTV')], max_length=100)),
                ('venue_photo', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('venue_photo_1', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('venue_photo_2', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('venue_photo_3', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('venue_photo_4', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('is_featured', models.BooleanField(max_length=100)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
