# Generated by Django 3.2.14 on 2022-07-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
