# Generated by Django 3.2.14 on 2022-07-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_decorator_dj_makeup_mehndi_pandit_transport_weddingplanner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dj',
            old_name='year_of_experience',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='mehndi',
            old_name='year_of_experience',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='pandit',
            old_name='year_of_experience',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='year_of_experience',
            new_name='experience',
        ),
        migrations.RemoveField(
            model_name='weddingplanner',
            name='year_of_experience',
        ),
        migrations.AddField(
            model_name='weddingplanner',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
