# Generated by Django 3.2.14 on 2022-07-24 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20220724_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dj',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='mehndi',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='pandit',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='weddingplanner',
            name='experience',
        ),
    ]
