# Generated by Django 3.2.14 on 2022-07-25 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20220724_1814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
