# Generated by Django 3.2.14 on 2022-07-25 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20220725_0729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Caterer',
        ),
        migrations.DeleteModel(
            name='Decorator',
        ),
        migrations.DeleteModel(
            name='DJ',
        ),
        migrations.DeleteModel(
            name='Makeup',
        ),
        migrations.DeleteModel(
            name='Mehndi',
        ),
        migrations.DeleteModel(
            name='Pandit',
        ),
        migrations.DeleteModel(
            name='Photographer',
        ),
        migrations.DeleteModel(
            name='Transport',
        ),
        migrations.DeleteModel(
            name='WeddingPlanner',
        ),
    ]
