# Generated by Django 3.2.14 on 2022-07-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20220725_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_1', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('photo_2', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('photo_3', models.ImageField(upload_to='photos/%y/%m/%d/')),
            ],
        ),
    ]
