# Generated by Django 3.2.14 on 2022-07-26 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_aboutimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutimage',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='aboutimage',
            name='photo_3',
        ),
    ]
