# Generated by Django 3.2.14 on 2022-07-23 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='event_date',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime),
        ),
    ]
