# Generated by Django 3.2.14 on 2022-07-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
