# Generated by Django 3.2.14 on 2022-07-24 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='event_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
