# Generated by Django 3.2.14 on 2022-07-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='guests',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='venue_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='venue_title',
        ),
        migrations.AddField(
            model_name='order',
            name='service_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
