# Generated by Django 3.2.14 on 2022-07-31 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
